Add helper view for creating user and pairing
tpazderka/django-mojeid-connect pull request #3
Opened 2018-07-09 14:03 UTC by tpazderka

2018-07-20 08:02 UTC, ziima requested changes

2018-07-20 08:02 UTC, ziima commented on django_mojeid_connect/templates/create_user.html
> +        {{ form.as_p}}
Missing space before closing bracket.

2018-07-20 08:02 UTC, ziima commented on django_mojeid_connect/views.py
> +    """View for creating and pairing user to mojeID."""
It would be better to describe it in more details.

2018-07-20 11:39 UTC, tpazderka commented
Fixed.

2018-07-26 06:42 UTC, ziima requested changes

2018-07-26 06:42 UTC, ziima commented on django_mojeid_connect/views.py
> +    If user is logged in, then the only requested attribute is `sub` which is then used to vreate the binding.
`... to create ...`

2018-07-26 08:34 UTC, tpazderka commented on django_mojeid_connect/views.py
> +    If user is logged in, then the only requested attribute is `sub` which is then used to vreate the binding.
Fixed.

2018-07-26 09:07 UTC, ziima approved these changes

2018-07-26 09:19 UTC, merged